# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Push Markdown to Notion
description: Push markdown changes to Notion
author: Josh Stern <josh.stern95@gmail.com>
branding:
  color: blue
  icon: book-open
inputs:
  notion-token:
    description: 'Notion integration token'
    required: true
runs:
  using: 'node16'
  main: 'dist/main.js'
